#!/bin/bash
#$1 = <action>/<dev>/<name>

[[ $EUID != 0 ]] && exit 1
shopt -s nullglob

# clean
for usb in /usb/*; do
    mountpoint -q "$usb" || rmdir "$usb"
done

IFS=/ read -r action dev name <<<"$1"
usb="$name-$dev"
if [[ "$action" == mount ]]; then
    mkdir -p "/usb/$usb"
    if mount "/dev/$dev" "/usb/$usb"; then
        username="$(ps au | awk '$11 == "xinit" { print $1; exit }')"
        [[ "$username" ]] && su "$username" xdg-open "/usb/$usb"
    else
        rmdir "/usb/$usb"
    fi
elif [[ "$action" == umount ]]; then
    [[ ! "$usb" || ! -d "/usb/$usb" ]] && exit 1
    umount "/usb/$usb"
    rmdir "/usb/$usb"
else
    exit 1
fi

exit 0
