#!/bin/bash
#$1 = <action>/<dev>/<name>

[[ $EUID != 0 ]] && exit 1

req="$(echo "$1" | tr / -)"
#debug
echo "$(date): $req" >> /tmp/usb-automount

# clean
for usb in $(ls /usb); do
    mountpoint -q "/usb/$usb" || rmdir "/usb/$usb"
done

action="$(echo "$req" | cut -d - -f 1)"
dev="$(echo "$req" | cut -d - -f 2)"
name="$(echo "$req" | cut -d - -f 3-)"
usb="$name-$dev"
if [[ "$action" == mount ]]; then
    mkdir -p "/usb/$usb"
    mount "/dev/$dev" "/usb/$usb" || rmdir "/usb/$usb"
elif [[ "$action" == umount ]]; then
    [[ "$usb" == "" || ! -d "/usb/$usb" ]] && exit 1
    umount "/usb/$usb"
    rmdir "/usb/$usb"
else
    exit 1
fi

exit 0
