#!/bin/bash
#$1 = <action>-<dev>-<name>

[[ $EUID != 0 ]] && exit 1

action="$(echo "$1" | cut -d - -f 1)"
dev="$(echo "$1" | cut -d - -f 2)"
name="$(echo "$1 | cut -d - -f 3-")"
usb="$name-$dev"
if [[ "$action" == mount ]]; then
    mkdir -p "/usb/$usb"
    mount "/dev/$dev" "/usb/$usb"
elif [[ "$action" == umount ]]; then
    [[ ! -d "/usb/$usb" ]] && exit 1
    umount "/usb/$usb"
    rmdir "/usb/$usb"
else
    exit 1
fi


